### ISSUE TITLE
Help needed to reset "Gallons Total" value monthly

### ISSUE THREAD

**Issue by gigawatts** [LowPowerLab/WaterMote#2]
I'm looking for a way to reset the Gallons Total metric monthly, so I can more easily compare it directly to my monthly bill.

I was looking at modifying the WaterMote sketch to reset the EEPROM address that stores the total gallons count when a specific value is received by the node, a RAW message something along the lines of "5:GALRESET". Then a monthly scheduled task on the Pi Gateway could send that message, triggering the reset.

My problem is, I can't quite find exactly the right EEPROM address that stores just the gallons total value, in order to zero it. Any hints, or example code, would be very helpful. I can likely figure out the rest, adding a "if incoming message matches X, trigger counter reset function"

**Comment by gigawatts** [comment]
Looks like I asked too soon, I just figured out the WaterMote side of this with the following code in the main loop:

```
    // listen for GALRST command
    if (radio.DATALEN == 6
        && radio.DATA[0]=='G' && radio.DATA[1]=='A' && radio.DATA[2]=='L' 
        && radio.DATA[3]=='R' && radio.DATA[4]=='S' && radio.DATA[5]=='T')
    {
      if (radio.ACKRequested()) radio.sendACK(); //send ACK sooner when an ACK is requested
      // erase the GAL data from eeprom to reset counter
      PulseCounter = PulseCounterVolatile = 1;
      EEPROM_Write_Counter(PulseCounter);
    }
```
Now, what would be the best way to send the message "GALRST" to this node on a fixed schedule from the Gateway? I am running v8.11.1 right now, but am working on the upgrade to v9.

**Comment by LowPowerLab** [comment]
Please take a look at other polling event examples that are shown in the [gateway app](https://github.com/LowPowerLab/RaspberryPi-Gateway). There are several such "poll" events which you could enable on your Sonar node and all you'd need to do is send your node a request.

One favor please: only open an **issue** here if there is an **issue**. General questions should go in [the forum](https://lowpowerlab.com/forum/coding-questions/).

**Comment by gigawatts** [comment]
oops, my bad. Thank you!
